name: Nagorik Frontend Deploy

on:
  push:
    branches:
      - dev  # Trigger workflow only on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Install sshpass for password-based SSH authentication
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Step 2: Deploy the application via SSH
      - name: Deploy via SSH
        env:
          PASSWORD: ${{ secrets.PASSWORD }}  # SSH password (stored as a GitHub secret)
          PORT: ${{ secrets.PORT }}          # SSH port (stored as a GitHub secret)
          USERNAME: ${{ secrets.USERNAME }}  # SSH username (stored as a GitHub secret)
          IP: ${{ secrets.IP }}              # Server IP address (stored as a GitHub secret)
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no -p "$PORT" "$USERNAME@$IP" << 'EOF'
            # Switch to root user
            sudo su

            # Navigate to the deployment directory
            cd /home/alwyzon/july-2025/july-2025

            # Stop running containers
            pm2 stop ecosystem.config.js

            # Navigate to the application directory
            cd /home/alwyzon/july-2025/july-2025

            # Pull the latest code changes from the repository
            git pull

            # Remove old Docker image to avoid conflicts
            pm2 start ecosystem.config.js

            # Build the new Docker image
            #docker build -t ncp-payment-gateway:latest /home/alwyzon/ncp-payment/ncp-payment-gateway

            # Navigate back to the deployment directory
            #cd /home/alwyzon/ncp-payment

            # Start the application in detached mode
            #docker compose up -d
          EOF