name: July 2025 Deploy

on:
  push:
    branches:
      - main  # Trigger workflow only on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Install sshpass for password-based SSH authentication
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Step 2: Deploy the application via SSH
      - name: Deploy via SSH
        env:
          PASSWORD: ${{ secrets.PASSWORDMAIN }}  # SSH password (stored as a GitHub secret)
          PORT: ${{ secrets.PORTMAIN }}          # SSH port (stored as a GitHub secret)
          USERNAME: ${{ secrets.USERNAMEMAIN }}  # SSH username (stored as a GitHub secret)
          IP: ${{ secrets.HOST }}              # Server IP address (stored as a GitHub secret)
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no -p "$PORT" "$USERNAME@$IP" << 'EOF'
            # Switch to root user
            sudo su

            # Navigate to the deployment directory
            cd /home/debian/july-2025/july-2025

            # Stop running containers
            docker compose down

            # Navigate to the application directory
            cd /home/debian/july-2025/july-2025

            # Pull the latest code changes from the repository
            git pull

            # Remove old Docker image to avoid conflicts
            docker rmi july-2025-frontend

            # Build the new Docker image
            docker build -t july-2025-frontend .

            # Navigate back to the deployment directory
            cd /home/debian/july-2025/july-2025

            # Start the application in detached mode
            docker compose up -d
          EOF